version: '3.8'

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - .env
  
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume: