version: '3.8'

services:
  miscursos-server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mis_cursos
      - POSTGRES_PASSWORD=mis_cursos
      - POSTGRES_DB=mis_cursos_dev

volumes:
  postgres_data: